version: '3'

volumes:
  base-data:
  ml_fastapi_db-data:
  ml_fastapi_nginx-data:
  redis-data:

services:
  ml_fastapi_db:
    image: postgres:15-alpine
    env_file:
      - .envs/.local/.postgres
    restart: always
    ports:
      - '5431:5432'
    volumes:
      - ml_fastapi_db-data:/var/lib/postgresql/data

  ml_fastapi_backend:
    restart: always
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    build:
      context: ./ml_fastapi_backend
      dockerfile: ./Dockerfile
    ports:
      - "8666:8000"
    command: |
        bash -c "
        while !</dev/tcp/ml_fastapi_db/5432; do sleep 1; done;
        gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --log-level=debug --timeout=60 --reload"
    depends_on:
      - ml_fastapi_db
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - base-data:/data
      - ./ml_fastapi_backend/:/code

  ml_fastapi_nginx:
    restart: always
    ports:
      - "0.0.0.0:80:80"
    env_file:
      - .envs/.local/.nginx
    depends_on:
      - ml_fastapi_backend
    build:
      context: ./ml_fastapi_nginx
      dockerfile: ./Dockerfile
    volumes:
        - ml_fastapi_nginx-data:/etc/letsencrypt

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6479:6379"
    volumes:
      - redis-data:/data
