version: '3.4'

x-fastapi-envs: &fastapi_envs
  environment:
    - PROJECT_NAME=ml_fastapi
    - NGINX_HOST=api-staging.mlfastapi.com
    - ENV=staging
    - POSTGRES_USER=mlfastapi
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_HOST=ml_fastapi_db
    - POSTGRES_DB=mlfastapi
    - POSTGRES_PORT=5432
    - VERSION=v1

x-default_deploy: &default_deploy
  deploy:
    mode: replicated
    replicas: 1
    restart_policy:
      condition: on-failure
      delay: 20s
      max_attempts: 6
      window: 120s
    update_config:
      parallelism: 1
      order: start-first

volumes:
  data-vol:
  ml_fastapi_dbdata-vol:
  ml_fastapi_nginxdata-vol:

services:
  ml_fastapi_db:
    image: postgres:15-alpine
    environment:
    labels:
      com.mlfastapi.container.name: mlfastapi-ml_fastapi_db
      com.mlfastapi.env: staging
      com.mlfastapi.project: mlfastapi-cloud
    volumes:
      - ml_fastapi_dbdata-vol:/var/lib/postgresql/data/
    <<: [*fastapi_envs, *default_deploy]

  ml_fastapi_nginx:
    image: ${REGISTRY}/ml_fastapi_nginx:${GITHUB_SHA}
    environment:
      - UPSTREAMS=/:ml_fastapi_backend:8000
      - NGINX_SERVER_NAME=api-staging.mlfastapi.com # without this, /admin redirects to https://_/
      - ENABLE_SSL=true
      - HTTPS_REDIRECT=true
      - CERTBOT_EMAIL=tomas.h.ambrogi@gmail.com
      - DOMAIN_LIST=api-staging.mlfastapi.com

    labels:
      com.mlfastapi.container.name: mlfastapi-ml_fastapi_nginx
      com.mlfastapi.env: staging
      com.mlfastapi.project: mlfastapi-cloud
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    volumes:
      - ml_fastapi_nginxdata-vol:/etc/letsencrypt
    <<: *default_deploy

  ml_fastapi_backend:
    image: ${REGISTRY}/ml_fastapi_backend:${GITHUB_SHA}
    environment:
    labels:
      com.mlfastapi.container.name: mlfastapi-ml_fastapi_backend
      com.mlfastapi.env: staging
      com.mlfastapi.project: mlfastapi-cloud
    <<: [*fastapi_envs, *default_deploy]
    volumes:
      - data-vol:/data
    command: bash -c "
      alembic upgrade head &&
      gunicorn src.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --log-level=info --timeout=120"
